/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sokoban;

import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Pablo Andres A
 */
public class Nivel1 extends javax.swing.JFrame {
    int pasos = 0;
    JLabel[] label = new JLabel[42];  
    ImageIcon image;
    /**
     * Creates new form Nivel
     */
    public Nivel1() {
        initComponents();
        labels();
        addKeyListener(new TAdapter());
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelMovimientos = new javax.swing.JLabel();
        jLabelPasos = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nivel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel2.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel3.setToolTipText("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel4.setToolTipText("");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel5.setToolTipText("");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel6.setToolTipText("");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel7.setToolTipText("");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel8.setToolTipText("");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/box80.png"))); // NOI18N
        jLabel9.setToolTipText("");

        jLabel10.setToolTipText("");
        jLabel10.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel10.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel11.setToolTipText("");
        jLabel11.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel11.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel11.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel12.setToolTipText("");
        jLabel12.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel12.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel12.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel13.setToolTipText("");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel14.setToolTipText("");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel15.setToolTipText("");

        jLabel16.setToolTipText("");
        jLabel16.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel16.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel16.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/box80.png"))); // NOI18N
        jLabel17.setToolTipText("");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/player80.png"))); // NOI18N
        jLabel18.setToolTipText("");

        jLabel19.setToolTipText("");
        jLabel19.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel19.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel19.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel20.setToolTipText("");
        jLabel20.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel20.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel20.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel21.setToolTipText("");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel22.setToolTipText("");

        jLabel23.setToolTipText("");
        jLabel23.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel23.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel23.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel24.setToolTipText("");

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Red_Point80.gif"))); // NOI18N
        jLabel25.setToolTipText("");

        jLabel26.setToolTipText("");
        jLabel26.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel26.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel26.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Red_Point80.gif"))); // NOI18N
        jLabel27.setToolTipText("");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel28.setToolTipText("");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel29.setToolTipText("");

        jLabel30.setToolTipText("");
        jLabel30.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel30.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel30.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel31.setToolTipText("");
        jLabel31.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel31.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel31.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel32.setToolTipText("");
        jLabel32.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel32.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel32.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel33.setToolTipText("");
        jLabel33.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel33.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel33.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel34.setToolTipText("");
        jLabel34.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabel34.setMinimumSize(new java.awt.Dimension(80, 80));
        jLabel34.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel35.setToolTipText("");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMovimientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMovimientos.setText("Movimientos minimos recomendados:");

        jLabelPasos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelPasos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPasos.setText("Pasos:");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel36.setToolTipText("");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel37.setToolTipText("");

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel38.setToolTipText("");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel39.setToolTipText("");

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel40.setToolTipText("");

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel41.setToolTipText("");

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall80.png"))); // NOI18N
        jLabel42.setToolTipText("");

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel43.setText("0");

        javax.swing.GroupLayout nivel1Layout = new javax.swing.GroupLayout(nivel1);
        nivel1.setLayout(nivel1Layout);
        nivel1Layout.setHorizontalGroup(
            nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nivel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel37)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel38)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel39)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel40)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel41)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel42))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMovimientos)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel22))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel24))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPasos)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel35)))
                .addGap(29, 29, 29))
        );
        nivel1Layout.setVerticalGroup(
            nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nivel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel13))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelMovimientos)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel22))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel24))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel25))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel27))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel28))
                    .addGroup(nivel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelPasos)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(0, 0, 0)
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void labels(){
        label[0] = jLabel1;
        label[1] = jLabel2;
        label[2] = jLabel3;
        label[3] = jLabel4;
        label[4] = jLabel5;
        label[5] = jLabel6;
        label[6] = jLabel7;
        label[7] = jLabel8;
        label[8] = jLabel9;
        label[9] = jLabel10;
        label[10] = jLabel11;
        label[11] = jLabel12;
        label[12] = jLabel13;
        label[13] = jLabel14;
        label[14] = jLabel15;
        label[15] = jLabel16;
        label[16] = jLabel17;
        label[17] = jLabel18;
        label[18] = jLabel19;
        label[19] = jLabel20;
        label[20] = jLabel21;
        label[21] = jLabel22;
        label[22] = jLabel23;
        label[23] = jLabel24;
        label[24] = jLabel25;
        label[25] = jLabel26;
        label[26] = jLabel27;
        label[27] = jLabel28;
        label[28] = jLabel29;
        label[29] = jLabel30;
        label[30] = jLabel31;
        label[31] = jLabel32;
        label[32] = jLabel33;
        label[33] = jLabel34;
        label[34] = jLabel35;
        label[35] = jLabel36;
        label[36] = jLabel37;
        label[37] = jLabel38;
        label[38] = jLabel39;
        label[39] = jLabel40;
        label[40] = jLabel41;
        label[41] = jLabel42;
    }
    
    private class TAdapter extends KeyAdapter {

        @Override
        public void keyPressed(KeyEvent e) {

            int key = e.getKeyCode();

            switch (key) {

                case KeyEvent.VK_LEFT:
                    pasos++;
                    jLabel43.setText(Integer.toString(pasos));
                    label[32].setIcon(new ImageIcon("D:\\Descargas\\11 SEMESTRE\\INTELIGENCIA ARTIFICIAL\\Sokoban-IA\\src\\imagenes\\wall80.png"));                
                    break;

                case KeyEvent.VK_RIGHT:
                    pasos++;
                    jLabel43.setText(Integer.toString(pasos));
                    label[32].setIcon(new ImageIcon("D:\\Descargas\\11 SEMESTRE\\INTELIGENCIA ARTIFICIAL\\Sokoban-IA\\src\\imagenes\\white.png"));                
                    break;

                case KeyEvent.VK_UP:
                    pasos++;
                    jLabel43.setText(Integer.toString(pasos));
                    label[32].setIcon(new ImageIcon("D:\\Descargas\\11 SEMESTRE\\INTELIGENCIA ARTIFICIAL\\Sokoban-IA\\src\\imagenes\\wall80.png"));                
                    break;

                case KeyEvent.VK_DOWN:
                    pasos++;
                    jLabel43.setText(Integer.toString(pasos));
                    label[32].setIcon(new ImageIcon("D:\\Descargas\\11 SEMESTRE\\INTELIGENCIA ARTIFICIAL\\Sokoban-IA\\src\\imagenes\\white.png"));
                    break;

                default:
                    break;
            }
            repaint();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMovimientos;
    private javax.swing.JLabel jLabelPasos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel nivel1;
    // End of variables declaration//GEN-END:variables
}
