/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sokoban;

/**
 *
 * @author Pablo Andres A
 */
public class Tableros extends javax.swing.JFrame {

    /**
     * Creates new form Tableros
     */
    public Tableros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jButtonNivel1 = new javax.swing.JButton();
        jButtonNivel = new javax.swing.JButton();
        jButtonNivel3 = new javax.swing.JButton();
        jButtonNivel4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nivel1.setBackground(new java.awt.Color(0, 0, 0));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 255, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("SOKOBAN");

        jButtonNivel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNivel1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNivel1.setText("NIVEL 2");
        jButtonNivel1.setBorderPainted(false);
        jButtonNivel1.setContentAreaFilled(false);
        jButtonNivel1.setFocusable(false);
        jButtonNivel1.setOpaque(false);

        jButtonNivel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNivel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNivel.setText("NIVEL 1");
        jButtonNivel.setBorderPainted(false);
        jButtonNivel.setContentAreaFilled(false);
        jButtonNivel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNivel.setFocusable(false);
        jButtonNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNivelMouseClicked(evt);
            }
        });

        jButtonNivel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNivel3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNivel3.setText("NIVEL 3");
        jButtonNivel3.setBorderPainted(false);
        jButtonNivel3.setContentAreaFilled(false);
        jButtonNivel3.setFocusable(false);

        jButtonNivel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNivel4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNivel4.setText("NIVEL 4");
        jButtonNivel4.setBorderPainted(false);
        jButtonNivel4.setContentAreaFilled(false);
        jButtonNivel4.setFocusable(false);

        javax.swing.GroupLayout nivel1Layout = new javax.swing.GroupLayout(nivel1);
        nivel1.setLayout(nivel1Layout);
        nivel1Layout.setHorizontalGroup(
            nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nivel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nivel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButtonNivel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNivel4)
                    .addComponent(jButtonNivel1))
                .addGap(115, 115, 115))
            .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nivel1Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jButtonNivel)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );
        nivel1Layout.setVerticalGroup(
            nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nivel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo)
                .addGap(82, 82, 82)
                .addComponent(jButtonNivel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNivel3)
                    .addComponent(jButtonNivel4))
                .addGap(71, 71, 71))
            .addGroup(nivel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nivel1Layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jButtonNivel)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(nivel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNivelMouseClicked
        Nivel1 nivel1 = new Nivel1();
        nivel1.setVisible(true);        
    }//GEN-LAST:event_jButtonNivelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tableros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tableros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNivel;
    private javax.swing.JButton jButtonNivel1;
    private javax.swing.JButton jButtonNivel3;
    private javax.swing.JButton jButtonNivel4;
    private javax.swing.JPanel nivel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
